### ISSUE TITLE
peek() sets hasPeek to true before calling read()

### ISSUE THREAD

**Issue by marianorenzi** [rickkas7/SC16IS740RK#3]
Hello, I was just reading the implementation and noticed that the hasPeek flag is set before calling read(), causing peek() to return init value for peekByte.

It immediately sets hasPeek to false, so read() itself isn't affected.

https://github.com/rickkas7/SC16IS740RK/blob/c12da73b722bb0b7b6713f1bbeb75126a1572aca/src/SC16IS740RK.cpp#L72

Thanks for the lib!

**Comment by rickkas7** [comment]
Yup. Those two lines need to be reversed. Version 0.0.2 of the library released. Thank you for the report!
